import React, { useEffect, useRef, useState } from "react";
import "./policypage.css";

const SECTIONS = [
    { id: "interpretation", title: "Interpretation & Definitions" },
    { id: "collecting", title: "Collecting & Using Your Data" },
    { id: "retention", title: "Retention of Your Data" },
    { id: "transfer", title: "Transfer of Your Data" },
    { id: "delete", title: "Deleting Your Data" },
    { id: "disclosure", title: "Disclosure of Your Data" },
    { id: "security", title: "Security" },
    { id: "children", title: "Children's & Minors' Privacy" },
    { id: "links", title: "Links to Other Websites" },
    { id: "changes", title: "Changes to This Policy" },
    { id: "contact", title: "Contact Us" },
];

const DEFINITIONS = [
    ["Account", "A unique account created for You to access Our Service or parts of Our Service."],
    ["Affiliate", 'An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the voting shares or equity.'],
    ["Company", '(referred to as "the Company", "We", "Us" or "Our") refers to Kalvium Portfolio.'],
    ["Cookies", "Small files placed on Your device by a website, containing details of Your browsing history on that site, among other uses."],
    ["Country/State", "Refers to Tamil Nadu, India."],
    ["Device", "Any device that can access the Service, such as a computer, a phone, or a tablet."],
    ["Personal Data", 'Any information that relates to an identified or identifiable individual. Used interchangeably with "Personal Information" unless a law uses a specific term.'],
    ["Service", "Refers to the Website."],
    ["Service Provider", "Any natural or legal person who processes data on behalf of the Company, to facilitate or provide the Service, or to assist in analyzing how it's used."],
    ["Usage Data", "Data collected automatically, generated by use of the Service or from the Service infrastructure itself (e.g. the duration of a page visit)."],
    ["User", "Any individual who accesses or uses the Service."],
    ["Website", "Refers to Kalvium Portfolio, accessible from kalvium-portfolio.vercel.app."],
    ["You", "The individual accessing or using the Service, or the company or legal entity on whose behalf they are doing so."],
];

const COOKIE_TYPES = [
    {
        name: "Necessary / Essential Cookies",
        type: "Session Cookies",
        purpose:
            "Essential to provide services available through the Website and to enable core features. They help authenticate users and prevent fraudulent use of accounts.",
    },
    {
        name: "Cookies Policy / Notice Acceptance Cookies",
        type: "Persistent Cookies",
        purpose:
            "Identify whether users have accepted the use of cookies on the Website and record the consent choices You have made, so We can honor those choices on future visits.",
    },
    {
        name: "Functionality Cookies",
        type: "Persistent Cookies",
        purpose:
            "Let Us remember choices You make when using the Website, such as login details or language preference, for a more personal experience.",
    },
];

const RETENTION = [
    {
        group: "Account Information",
        items: ["User accounts — retained for the duration of Your account relationship, plus up to 24 months after closure to handle post-termination issues or disputes."],
    },
    {
        group: "Customer Support Data",
        items: [
            "Support tickets & correspondence — up to 24 months from ticket closure, to resolve follow-ups and defend against potential claims.",
            "Chat transcripts — up to 24 months, for quality assurance and staff training.",
        ],
    },
    {
        group: "Usage Data",
        items: [
            "Website analytics (cookies, IP addresses, device identifiers) — up to 24 months from collection.",
            "Server logs (IP addresses, access times) — up to 24 months, for security monitoring and troubleshooting.",
        ],
    },
];

export default function PrivacyPolicy() {
    const [active, setActive] = useState(SECTIONS[0].id);
    const [navOpen, setNavOpen] = useState(false);
    const sectionRefs = useRef(new Map());

    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) setActive(entry.target.id);
                });
            },
            { rootMargin: "-15% 0px -70% 0px", threshold: 0 }
        );
        sectionRefs.current.forEach((el) => el && observer.observe(el));
        return () => observer.disconnect();
    }, []);

    const setRef = (id) => (el) => {
        sectionRefs.current.set(id, el);
    };

    const goTo = (id) => (e) => {
        e.preventDefault();
        sectionRefs.current.get(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
        setNavOpen(false);
    };

    return (
        <div className="pp-page">


            <div className="pp-card">
                <div className="pp-header">
                    <div className="pp-brand">
                        <span className="pp-logo-dot" />
                        <span className="pp-brand-name">Kalvium Portfolio</span>
                    </div>
                    <span className="pp-updated-pill">Last updated Aug 25, 2026</span>
                </div>

                <aside className="pp-sidebar">
                    <button
                        className="pp-nav-toggle"
                        onClick={() => setNavOpen((v) => !v)}
                        aria-expanded={navOpen}
                    >
                        On this page <span className="pp-caret">⌄</span>
                    </button>
                    <div className="pp-toc-label">On this page</div>
                    <ul className={`pp-toc ${navOpen ? "open" : ""}`}>
                        {SECTIONS.map((s) => (
                            <li key={s.id}>
                                <a
                                    href={`#${s.id}`}
                                    onClick={goTo(s.id)}
                                    className={active === s.id ? "active" : ""}
                                >
                                    {s.title}
                                </a>
                            </li>
                        ))}
                    </ul>
                </aside>

                <main className="pp-main">
                    <h1 className="pp-h1">Privacy Policy</h1>
                    <div className="pp-intro">
                        <p>
                            This Privacy Policy describes Our policies and procedures on the collection,
                            use and disclosure of Your information when You use the Service, and tells
                            You about Your privacy rights and how the law protects You.
                        </p>
                        <p>
                            We use Your Personal Data to provide and improve the Service. We collect,
                            use, and disclose Your information as described in this Privacy Policy and,
                            where required by applicable law, only where We have a valid legal basis to
                            do so, including Your consent (where consent is required).
                        </p>
                    </div>

                    {/* Interpretation & Definitions */}
                    <section id="interpretation" ref={setRef("interpretation")} className="pp-section">
                        <h2>Interpretation &amp; Definitions</h2>
                        <div className="pp-content">
                            <h3>Interpretation</h3>
                            <p>
                                Words whose initial letters are capitalized have meanings defined under
                                the following conditions. These definitions apply whether the terms
                                appear in singular or plural.
                            </p>
                            <h3>Definitions</h3>
                            <dl className="pp-glossary">
                                {DEFINITIONS.map(([term, def]) => (
                                    <div className="pp-term" key={term}>
                                        <dt>{term}</dt>
                                        <dd>{def}</dd>
                                    </div>
                                ))}
                            </dl>
                        </div>
                    </section>

                    {/* Collecting & Using */}
                    <section id="collecting" ref={setRef("collecting")} className="pp-section">
                        <h2>Collecting &amp; Using Your Data</h2>
                        <div className="pp-content">
                            <h4>Personal Data</h4>
                            <p>
                                While using Our Service, We may ask You to provide certain personally
                                identifiable information that can be used to contact or identify You,
                                including but not limited to:
                            </p>
                            <ul>
                                <li>Email address</li>
                                <li>First name and last name</li>
                            </ul>

                            <h4>Usage Data</h4>
                            <p>
                                Usage Data is collected automatically when using the Service. It may
                                include Your device's IP address, browser type and version, the pages
                                You visit, the time and date of Your visit, time spent on those pages,
                                unique device identifiers, and other diagnostic data.
                            </p>
                            <p>
                                When You access the Service through a mobile device, We may also collect
                                the type of device, its unique ID, mobile IP address, operating system,
                                browser type, and similar diagnostic data.
                            </p>

                            <h4>Tracking Technologies &amp; Cookies</h4>
                            <p>
                                We use tracking technologies to track activity on Our Service and to
                                improve it. Cookies can be "Persistent" (remain until deleted or expired)
                                or "Session" (deleted once You close Your browser). Where required by
                                law, non-essential cookies are used only with Your consent, which You may
                                withdraw at any time.
                            </p>
                            <div className="pp-cookie-grid">
                                {COOKIE_TYPES.map((c) => (
                                    <div className="pp-cookie-card" key={c.name}>
                                        <h5>{c.name}</h5>
                                        <span className="pp-cookie-meta">{c.type}</span>
                                        <p>{c.purpose}</p>
                                    </div>
                                ))}
                            </div>

                            <h4>Use of Your Personal Data</h4>
                            <p>The Company may use Personal Data for the following purposes:</p>
                            <ul>
                                <li><strong>To provide and maintain Our Service</strong>, including monitoring its usage.</li>
                                <li><strong>To manage Your Account</strong> as a registered user of the Service.</li>
                                <li><strong>For the performance of a contract</strong>, including products or services You've purchased.</li>
                                <li><strong>To contact You</strong> by email, phone, SMS, or push notification about updates or security matters.</li>
                                <li><strong>To provide news and offers</strong> similar to what You've already purchased or inquired about, only where permitted by applicable law — You may opt out at any time.</li>
                                <li><strong>To manage Your requests</strong> to Us.</li>
                                <li><strong>For business transfers</strong>, such as a merger, sale, or reorganization.</li>
                                <li><strong>For other purposes</strong>, such as data analysis and improving Our Service and Your experience.</li>
                            </ul>

                            <p>We may share Your Personal Data in these situations:</p>
                            <ul>
                                <li><strong>With Service Providers</strong>, to monitor and analyze use of the Service.</li>
                                <li><strong>For business transfers</strong>, in connection with a merger, sale, or acquisition.</li>
                                <li><strong>With Affiliates</strong>, who will be required to honor this Privacy Policy.</li>
                                <li><strong>With other users</strong>, in any public areas of the Service.</li>
                                <li><strong>With Your consent</strong>, for any other disclosed purpose.</li>
                            </ul>

                            <h4>Text Messages Privacy Notice</h4>
                            <p>
                                If You opt in to SMS, We collect Your phone number, the date and method
                                of consent, and delivery/read information. Mobile information is never
                                shared with or sold to third parties for marketing purposes, except
                                Service Providers required to technically deliver the texts. Messages
                                may relate to customer support, account notifications, delivery updates,
                                authentication (OTP), security alerts, or marketing. Reply STOP to
                                opt out, HELP for support. Message &amp; data rates may apply.
                            </p>
                        </div>
                    </section>

                    {/* Retention */}
                    <section id="retention" ref={setRef("retention")} className="pp-section">
                        <h2>Retention of Your Data</h2>
                        <div className="pp-content">
                            <p>
                                The Company retains Your Personal Data only as long as necessary for the
                                purposes set out in this Policy, to comply with legal obligations,
                                resolve disputes, and enforce agreements. Where possible, We apply
                                shorter retention periods and reduce identifiability by deleting,
                                aggregating, or anonymizing data. Unless stated otherwise, the periods
                                below are maximums — We may delete or anonymize sooner.
                            </p>
                            {RETENTION.map((r) => (
                                <div className="pp-retention-group" key={r.group}>
                                    <h5>{r.group}</h5>
                                    <ul>
                                        {r.items.map((item) => (
                                            <li key={item}>{item}</li>
                                        ))}
                                    </ul>
                                </div>
                            ))}
                            <p>We may retain data longer for legal obligations, legal claims, Your explicit request, or technical backup limitations. When retention periods expire, We delete, retain limited encrypted backups, or irreversibly anonymize the data.</p>
                        </div>
                    </section>

                    {/* Transfer */}
                    <section id="transfer" ref={setRef("transfer")} className="pp-section">
                        <h2>Transfer of Your Data</h2>
                        <div className="pp-content">
                            <p>
                                Your information is processed at the Company's operating offices and
                                wherever the processing parties are located, which may be outside Your
                                jurisdiction. Where required by law, We ensure appropriate safeguards
                                and supplementary measures are in place, and no transfer takes place
                                unless adequate controls exist to secure Your data.
                            </p>
                        </div>
                    </section>

                    {/* Delete */}
                    <section id="delete" ref={setRef("delete")} className="pp-section">
                        <h2>Deleting Your Data</h2>
                        <div className="pp-content">
                            <p>
                                You have the right to delete, or ask Us to help delete, the Personal
                                Data We've collected. You may update, amend, or delete Your information
                                by signing in to Your Account and visiting account settings, or by
                                contacting Us directly. We may need to retain certain information where
                                We have a legal obligation to do so.
                            </p>
                        </div>
                    </section>

                    {/* Disclosure */}
                    <section id="disclosure" ref={setRef("disclosure")} className="pp-section">
                        <h2>Disclosure of Your Data</h2>
                        <div className="pp-content">
                            <h4>Business Transactions</h4>
                            <p>If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We'll provide notice before it becomes subject to a different Privacy Policy.</p>
                            <h4>Law Enforcement</h4>
                            <p>We may disclose Your Personal Data if required by law or in response to valid requests by public authorities.</p>
                            <h4>Other Legal Requirements</h4>
                            <p>We may disclose Your Personal Data where We believe in good faith it's necessary to:</p>
                            <ul>
                                <li>Comply with a legal obligation</li>
                                <li>Protect the rights or property of the Company</li>
                                <li>Prevent or investigate wrongdoing related to the Service</li>
                                <li>Protect the personal safety of Users or the public</li>
                                <li>Protect against legal liability</li>
                            </ul>
                        </div>
                    </section>

                    {/* Security */}
                    <section id="security" ref={setRef("security")} className="pp-section">
                        <h2>Security</h2>
                        <div className="pp-content">
                            <p>
                                The security of Your Personal Data matters to Us, but no method of
                                transmission or electronic storage is 100% secure. While We use
                                commercially reasonable means to protect Your data, We cannot guarantee
                                absolute security.
                            </p>
                        </div>
                    </section>

                    {/* Children */}
                    <section id="children" ref={setRef("children")} className="pp-section">
                        <h2>Children's &amp; Minors' Privacy</h2>
                        <div className="pp-content">
                            <p>
                                The Service is not directed to, and We do not knowingly collect Personal
                                Information from, anyone under the age of 16. If You are a parent or
                                guardian and believe Your child has provided Us with Personal
                                Information, please contact Us — We'll remove it as soon as reasonably
                                possible.
                            </p>
                            <p>
                                Where a jurisdiction sets a higher consent age than 16, and We rely on
                                consent as a legal basis, We may require parental or guardian consent
                                before collecting and using that User's Personal Information.
                            </p>
                        </div>
                    </section>

                    {/* Links */}
                    <section id="links" ref={setRef("links")} className="pp-section">
                        <h2>Links to Other Websites</h2>
                        <div className="pp-content">
                            <p>
                                Our Service may link to other websites We don't operate. We strongly
                                advise reviewing the Privacy Policy of every site You visit — We have no
                                control over, and assume no responsibility for, third-party content or
                                practices.
                            </p>
                        </div>
                    </section>

                    {/* Changes */}
                    <section id="changes" ref={setRef("changes")} className="pp-section">
                        <h2>Changes to This Policy</h2>
                        <div className="pp-content">
                            <p>
                                We may update this Privacy Policy from time to time. We'll notify You by
                                posting the new Policy on this page, and where the change is
                                significant, via email or a prominent notice before it takes effect. The
                                "Last updated" date above reflects the most recent revision.
                            </p>
                        </div>
                    </section>

                    {/* Contact */}
                    <section id="contact" ref={setRef("contact")} className="pp-section">
                        <h2>Contact Us</h2>
                        <div className="pp-content">
                            <p>If You have any questions about this Privacy Policy, You can reach Us here:</p>
                            <div className="pp-contact-card">
                                <div>
                                    <div className="pp-contact-label">Email</div>
                                    <a className="pp-email" href="mailto:kpm-squad@googlegroups.com">kpm-squad@googlegroups.com</a>
                                </div>
                                <a className="pp-contact-btn" href="mailto:kpm-squad@googlegroups.com">
                                    Send an email
                                </a>
                            </div>
                        </div>
                    </section>

                    <div className="pp-footer">Kalvium Portfolio — Privacy Policy — Rev. 2026-08-25</div>
                </main>
            </div>
        </div>
    );
}